"""switched to perspective in Move

Revision ID: 652e9a04f877
Revises: e239b1391237
Create Date: 2020-12-17 10:53:00.255088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652e9a04f877'
down_revision = 'e239b1391237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perspective', sa.String(length=1), nullable=True))
        batch_op.drop_column('color_to_move')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_to_move', sa.VARCHAR(length=1), nullable=True))
        batch_op.drop_column('perspective')

    # ### end Alembic commands ###
