"""added book_move

Revision ID: 78c9010f8aaf
Revises: 652e9a04f877
Create Date: 2020-12-17 18:08:03.433363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c9010f8aaf'
down_revision = '652e9a04f877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_move', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_my_move')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_my_move', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('book_move')

    # ### end Alembic commands ###
