"""added last_review to Moves and created User relationship

Revision ID: 965e42327ea2
Revises: b6e3e9a0ef83
Create Date: 2020-12-16 15:46:35.796013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965e42327ea2'
down_revision = 'b6e3e9a0ef83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_review', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.drop_column('last_review')

    # ### end Alembic commands ###
