"""added SMTwo integration

Revision ID: b6e3e9a0ef83
Revises: f39051a2ca9b
Create Date: 2020-12-16 14:28:41.529497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e3e9a0ef83'
down_revision = 'f39051a2ca9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('easiness', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('interval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('next_review', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('repetitions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.drop_column('repetitions')
        batch_op.drop_column('next_review')
        batch_op.drop_column('interval')
        batch_op.drop_column('easiness')

    # ### end Alembic commands ###
