"""added Moves table

Revision ID: c9b0d072e5e4
Revises: 6c07217d562e
Create Date: 2020-12-16 12:47:37.172348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b0d072e5e4'
down_revision = '6c07217d562e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('fen', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['moves.id'], name=op.f('fk_moves_parent_id_moves')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_moves_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moves'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    # ### end Alembic commands ###
